spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
#    username: xuezhou
#    password: password
    url: jdbc:mysql://47.103.142.85:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
    username: root
    password: Luan123456
#    url: jdbc:mysql://58.210.33.107:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
#    username: root
#    password: Luan123456
#    url: jdbc:mysql://101.132.105.124:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
#    username: root
#    password: Luan123456
#    url: jdbc:mysql://123.207.168.102:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
#    username: fancy
#    password: fancy!888
#    url: jdbc:mysql://47.96.135.182:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
#    username: root
#    password: newpasswrod

    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

  jmx:
    enabled: false

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  servlet:
    content-type: text/html
  mode: LEGACYHTML5
  cache: false
  encoding: UTF-8
  enable-spring-el-compiler: true
mvc:
  static-path-pattern: /**
  view:
    prefix: classpath:resources/
    suffix: .html
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jinshi.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#logging:
#  level:
#    com:
#      jinshi:
#        mapper : debug


#  jpa:
#  mybatis:
#  ddl-auto: update
#  show-sql: true
server:
  port: 8080


#昆山建行支付参数
ccb:
  MERCHANTID: 105007473994127 # 商户代码,固定写死的,需要申请
  POSID: 041287924 # 商户柜台代码,固定写死的,需要申请
  BRANCHID: 322000000 # 分行代码,固定写死的,需要申请
  CURCODE: 01 #付款币种,固定写01 代表支付金额
  TXCODE: 530550 # 由建行统一分配为530550
  PUB32TR2: e1b154dc1963b6869eb5dad7020111 # 公钥后30位
